drop table if exists
accounts,
roles,
account_roles,
sessions,
year3and4
cascade;

CREATE TABLE accounts (
	user_id serial PRIMARY KEY,
	firstName VARCHAR ( 100 ) NOT NULL,
	lastName VARCHAR ( 100 )  NOT NULL,
	userName VARCHAR ( 100 ) UNIQUE NOT NULL,
	password VARCHAR ( 100 ) NOT NULL,
	email VARCHAR ( 255 )  NOT NULL,
	created_on TIMESTAMP,
    last_login TIMESTAMP 
);

CREATE TABLE roles(
   role_id serial PRIMARY KEY,
   role_name VARCHAR (255) UNIQUE NOT NULL
);

CREATE TABLE account_roles (
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  grant_date TIMESTAMP,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (role_id) REFERENCES roles (role_id),
  FOREIGN KEY (user_id) REFERENCES accounts (user_id)
);


CREATE TABLE sessions (
session_id serial PRIMARY KEY,
session_key INT NOT NULL,
user_id INT REFERENCES accounts (user_id),
correnct int,
incorrect int	
);

CREATE TABLE year3and4(
word_id serial PRIMARY KEY,
word varchar(50)
);


INSERT INTO year3and4(word)
values
  ('accident'),
  ('accidentally'),
  ('actual'),
  ('actually'),
  ('address'),
  ('answer'),
  ('appear'),
  ('arrive'),
  ('believe'),
  ('bicycle'),
  ('breath'),
  ('breathe'),
  ('build'),
  ('busy'),
  ('business'),
  ('calendar'),
  ('caught'),
  ('centre'),
  ('century'),
  ('certain'),
  ('circle'),
  ('complete'),
  ('consider'),
  ('continue'),
  ('decide'),
  ('describe'),
  ('different'),
  ('difficult'),
  ('disappear'),
  ('early'),
  ('earth'),
  ('eight'),
  ('eighth'),
  ('enough'),
  ('exercise'),
  ('experience'),
  ('experiment'),
  ('extreme'),
  ('famous'),
  ('favourite'),
  ('February'),
  ('forward'),
  ('forwards'),
  ('fruit'),
  ('grammar'),
  ('group'),
  ('guard'),
  ('guide'),
  ('heard'),
  ('heart'),
  ('height'),
  ('history'),
  ('imagine'),
  ('increase'),
  ('important'),
  ('interest'),
  ('island'),
  ('knowledge'),
  ('learn'),
  ('length'),
  ('library'),
  ('material'),
  ('medicine'),
  ('mention'),
  ('minute'),
  ('natural'),
  ('naughty'),
  ('notice'),
  ('occasion'),
  ('occasionally'),
  ('often'),
  ('opposite'),
  ('ordinary'),
  ('particular'),
  ('peculiar'),
  ('perhaps'),
  ('popular'),
  ('position'),
  ('possess'),
  ('possession'),
  ('possible'),
  ('potatoes'),
  ('pressure'),
  ('probably'),
  ('promise'),
  ('purpose'),
  ('quarter'),
  ('question'),
  ('recent'),
  ('regular'),
  ('reign'),
  ('remember'),
  ('sentence'),
  ('separate'),
  ('special'),
  ('straight'),
  ('strange'),
  ('strength'),
  ('suppose'),
  ('surprise'),
  ('therefore'),
  ('though'),
  ('although'),
  ('thought'),
  ('through'),
  ('various'),
  ('weight'),
  ('woman'),
  ('women');
